locales:
  rmn:
    name: Romani Keyboards
    description: >-
      Mobile OS keyboards for the Romani language from the Divvun group
      at UiT.
  en:
    name: Romani Keyboards
    description: >-
      Mobile OS keyboards for the Romani language from the Divvun group
      at UiT.
  nb:
    name: Romany tastatur
    description: Mobiltastatur for Romany fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta

