locales:
  rmn:
    name: Romani ramojbaskiri tastatura
    description: >-
      Tastatura e romane čhibake ki Švedija, kerdi kotar o Isof
      ko maškarbutikeribe e grupencar Divvun thaj Giellatekno kotar o univerziteti ko Tromso.
  en:
    name: Romani Keyboards
    description: >-
      Keyboards for Romani (Sweden), made by ISOF in cooperation
      with the Divvun and Giellatekno groups at UiT.
  nb:
    name: Romanitastatur
    description: >-
      Tastatur for romani (Sverige), utvikla av ISOF i samarbeid
      med Divvun- og Giellatekno-gruppene ved UiT.
  nn:
    name: Romanitastatur
    description: >-
      Tastatur for romani (Sverige), utvikla av ISOF i samarbeid
      med Divvun- og Giellatekno-gruppene ved UiT.
  sv:
    name: Romanitangentbord
    description: >-
      Tangentbord för romani (Sverige), tagit fram av ISOF i samarbete
      med Divvun- och Giellatekno-grupperna vid UiT.

author: 'The Divvun Group, UiT Norgga árktalaš universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga árktalaš universitehta

