locales:
  rmn:
    name: Romany Arli Keyboards
    description: >-
      Mobile OS keyboards for the Romany Arli language from the Divvun group
      at UiT.
  en:
    name: Romany Arli Keyboards
    description: >-
      Mobile OS keyboards for the Romany Arli language from the Divvun group
      at UiT.
  nb:
    name: Romany Arli tastatur
    description: Mobiltastatur for Romany Arli fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
